version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  release:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npx semantic-release
workflows:
    release-only:
      jobs:
        - release
